from abc import abstractmethod, ABC
from typing import List

class Provider(ABC):
    """
    Abstract base class for Large Language Model (LLM) providers.
    Defines the interface for chat and embedding functionalities.
    """

    def chat(
            self,
            prompt: str,
            model: str,
            system_prompt: str = None,
            assistant_prompt: str = None,
            tools: dict = None,
            config: dict = None
    ) -> any:
        """
        Chat with a given prompt using the specified model.
        If tools are provided, use agentic_chat; otherwise, use simple_chat.

        :param prompt: The input prompt string to generate a response for.
        :param model: The model identifier to use for generating responses.
        :param system_prompt: The system prompt to set the context for the chat.
        :param assistant_prompt: The assistant prompt to guide the chat responses.
        :param tools: Optional, a dictionary of external tools to assist the chat.
        :param config: Optional, configuration parameters for the chat session.

        :return: the stream of responses generated by the agentic chat process.
        """
        if tools is not None:
            return self.agentic_chat(prompt=prompt,
                                     model=model,
                                     system_prompt=system_prompt,
                                     assistant_prompt=assistant_prompt,
                                     tools=tools,
                                     config=config
                                     )
        else:
            return self.simple_chat(prompt=prompt,
                                    model=model,
                                    system_prompt=system_prompt,
                                    config=config)

    @abstractmethod
    def agentic_chat(
            self,
            prompt: str,
            model: str,
            system_prompt: str,
            assistant_prompt: str,
            tools: dict,
            config: dict = None) -> any:
        """
        Chat with a given prompt using the specified model and tools.
        This function manages interactions with external tools to enhance responses.

        :param prompt: The input prompt string to generate a response for.
        :param model: The model identifier to use for generating responses.
        :param system_prompt: The system prompt to set the context for the chat.
        :param assistant_prompt: The assistant prompt to guide the chat responses.
        :param tools: A dictionary of external tools to assist the chat.
        :param config: Optional configuration parameters for the chat session.

        :return: the stream of responses generated by the agentic chat process.
        """
        pass

    @abstractmethod
    def simple_chat(
            self,
            prompt: str,
            model: str,
            system_prompt: str = None,
            config: dict = None) -> any:
        """
        Chat with a given prompt using the specified model without external tools.

        :param prompt: The input prompt string to generate a response for.
        :param model: The model identifier to use for generating responses.
        :param system_prompt: The system prompt to set the context for the chat.
        :param config: Optional configuration parameters for the chat session.

        :return: the stream of responses generated by the simple chat process.
        """

        pass

    @abstractmethod
    def embed(
            self,
            text: str,
            embedding_model: str
    ) -> List[float]:
        """
        Embed the given string using the specified embedding model.

        :param text: The input string to be embedded.
        :param embedding_model: The embedding model identifier to use for generating embeddings.

        :return: the embedding vector generated by the embedding model.
        """
        pass
